name: Python linting
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.5, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip dir
      uses: actions/cache@v1
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('galaxy root/requirements.txt') }}
    - name: Install tox
      run: pip install tox
    - name: run tests
      run: tox -e lint
